logging:
  level:
    root: info
  file:
    path: "/docker/adelyn/blog/logs"

server:
  port: 9099
  servlet:
    context-path: /blog

adelyn:
  blog:
    oss:
      domain: ${ADELYN_BLOG_OSS_DOMAIN}
      bucketName: ${ADELYN_BLOG_OSS_BUCKET_NAME}
      accessKeyId: ${ADELYN_BLOG_OSS_ACCESS_KEY_ID}
      accessKeySecret: ${ADELYN_BLOG_OSS_ACCESS_KEY_SECRET}
  auth:
    unauth:
      uriPatterns: /**/public/**
  elasticsearch:
    host: ${ADELYN_ELASTICSEARCH_HOST}
    port: ${ADELYN_ELASTICSEARCH_PORT}

spring:
  application:
    name: adelyn-blog
  #启动虚拟线程的必须配置
  threads:
    virtual:
      # 启用虚拟线程技术，增加系统并发能力
      enabled: true
  servlet:
    multipart:
      max-file-size: 1000MB        # 设置单个文件最大大小为1000MB
      max-request-size: 10000MB    # 设置多个文件大小为10000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}


